package classe;

public class PrimeiroTrauma {

	static int a = 3;
	int b = 4;
	public static void main(String[] args) {
		
		System.out.println(a); 
		
		PrimeiroTrauma p = new PrimeiroTrauma();
		System.out.println(p.b);
		
		// Custom input string
        String str = "G\r\n"
        		+ "6\r\n"
        		+ "P\r\n"
        		+ "l\r\n"
        		+ "a\r\n"
        		+ "y\r\n"
        		+ "C\r\n"
        		+ "h\r\n"
        		+ "i\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "S\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "9\r\n"
        		+ "0\r\n"
        		+ "N\r\n"
        		+ "o\r\n"
        		+ "t\r\n"
        		+ "e\r\n"
        		+ "7\r\n"
        		+ "N\r\n"
        		+ "a\r\n"
        		+ "c\r\n"
        		+ "i\r\n"
        		+ "o\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "l\r\n"
        		+ "S\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "1\r\n"
        		+ "3\r\n"
        		+ "0\r\n"
        		+ "K\r\n"
        		+ "5\r\n"
        		+ "2\r\n"
        		+ "C\r\n"
        		+ "h\r\n"
        		+ "i\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "C\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "1\r\n"
        		+ "3\r\n"
        		+ "0\r\n"
        		+ "A\r\n"
        		+ "1\r\n"
        		+ "0\r\n"
        		+ "s\r\n"
        		+ "N\r\n"
        		+ "a\r\n"
        		+ "c\r\n"
        		+ "i\r\n"
        		+ "o\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "l\r\n"
        		+ "S\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "1\r\n"
        		+ "2\r\n"
        		+ "0\r\n"
        		+ "J\r\n"
        		+ "6\r\n"
        		+ "+\r\n"
        		+ "N\r\n"
        		+ "a\r\n"
        		+ "c\r\n"
        		+ "i\r\n"
        		+ "o\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "l\r\n"
        		+ "1\r\n"
        		+ "0\r\n"
        		+ "0\r\n"
        		+ "G\r\n"
        		+ "6\r\n"
        		+ "P\r\n"
        		+ "l\r\n"
        		+ "a\r\n"
        		+ "y\r\n"
        		+ "C\r\n"
        		+ "h\r\n"
        		+ "i\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "C\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "1\r\n"
        		+ "0\r\n"
        		+ "0\r\n"
        		+ "N\r\n"
        		+ "o\r\n"
        		+ "t\r\n"
        		+ "e\r\n"
        		+ "7\r\n"
        		+ "N\r\n"
        		+ "a\r\n"
        		+ "c\r\n"
        		+ "i\r\n"
        		+ "o\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "l\r\n"
        		+ "C\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "1\r\n"
        		+ "6\r\n"
        		+ "0\r\n"
        		+ "K\r\n"
        		+ "5\r\n"
        		+ "2\r\n"
        		+ "N\r\n"
        		+ "a\r\n"
        		+ "c\r\n"
        		+ "S\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "1\r\n"
        		+ "2\r\n"
        		+ "0\r\n"
        		+ "A\r\n"
        		+ "1\r\n"
        		+ "0\r\n"
        		+ "s\r\n"
        		+ "c\r\n"
        		+ "h\r\n"
        		+ "i\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "C\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "8\r\n"
        		+ "0\r\n"
        		+ "J\r\n"
        		+ "7\r\n"
        		+ "I\r\n"
        		+ "n\r\n"
        		+ "c\r\n"
        		+ "e\r\n"
        		+ "l\r\n"
        		+ "l\r\n"
        		+ "8\r\n"
        		+ "0\r\n"
        		+ "G\r\n"
        		+ "6\r\n"
        		+ "P\r\n"
        		+ "l\r\n"
        		+ "a\r\n"
        		+ "y\r\n"
        		+ "N\r\n"
        		+ "a\r\n"
        		+ "c\r\n"
        		+ "i\r\n"
        		+ "o\r\n"
        		+ "n\r\n"
        		+ "a\r\n"
        		+ "l\r\n"
        		+ "S\r\n"
        		+ "/\r\n"
        		+ "A\r\n"
        		+ "r\r\n"
        		+ "o\r\n"
        		+ "1\r\n"
        		+ "3\r\n"
        		+ "0";
        String[] arrOfStr = str.split("\r\n");
  
        for (String a : arrOfStr)
            System.out.print(a);

	}

}
